OnlineShop/Areas/Admin/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Dao;
using Model.EF;
namespace OnlineShop.Areas.Admin.Controllers
{
    public class FeedbackController : Controller
    {
        // GET: Admin/Feedback
        public ActionResult Index(string searchString, int page = 1, int pageSize = 10)
        {
            var model = new FeedbackDao().ListAllPagingFeedBack(searchString, page, pageSize);
            ViewBag.SearchString = searchString;

            return View(model);
        }
    }
}

OnlineShop/Areas/Admin/Views/Feedback/Index.cshtml
@model PagedList.IPagedList<Model.EF.Feedback>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Quản lý feedback";
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}
@section header{
    Danh sách Feedback
}

@section jsFooter{

}
<div class="row">

    <div class="col-lg-12">

        <div class="panel panel-default">
            @*<div class="panel-heading">
                Danh sách tin tức
            </div>*@

            <!-- /.panel-heading -->
            <div class="panel-body">
                @using (Html.BeginForm("Index", "Feedback", FormMethod.Get))
                {
                    <div class="row form-group">
                        <div class="col-lg-12">
                            <div class="col-md-4">
                                <input type="text" value="@ViewBag.SearchString" class="form-control" name="searchString" placeholder="Từ khóa" />
                            </div>
                            <div class="col-md-4">
                                <button type="submit" class="btn btn-success">Tìm kiếm</button>                                
                            </div>
                        </div>
                    </div>
                }

                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Tên</th>
                                <th>Phone</th>
                                <th>Email</th>
                                <th>Address</th>
                                <th>Ngày</th>                               
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr id="row_@item.ID">

                                    <td>@item.Name</td>
                                    <td>@item.Phone</td>
                                    <td>@item.Email</td>
                                    <td>@item.Address</td>
                                    <td>@item.CreatedDate</td>                                      
                                    <td>                                        
                                        @Ajax.ActionLink("Xoá", "Delete", new { @id = item.ID }, new AjaxOptions
                                   {
                                       Confirm = "Bạn có muốn xoá bản ghi này?",
                                       OnComplete = "$('#row_" + @item.ID + "').remove()",
                                       HttpMethod = "Delete"
                                   })
                                    </td>
                                </tr>
                            }


                        </tbody>
                    </table>
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString }))
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>